data_ingestion:
  raw_data_path: data/raw/loan_data.csv
  processed_data_path: data/processed/loan.csv

data_preparation:
  processed_data_path: data/processed/loan.csv
  train_path: data/train/train_data.csv
  test_path: data/test/test_data.csv
  test_size_pct: 0.2
  random_seed: 42

data_transformation:
  train_path: data/train/train_data.csv
  test_path: data/test/test_data.csv
  train_array_path: data/train/train_array.npy
  test_array_path: data/test/test_array.npy
  preprocessor_path: models/preprocessors/preprocessor.pkl

model_trainer:
  train_array_path: data/train/train_array.npy
  test_array_path: data/test/test_array.npy
  model_path: models/trained/model.pkl
  scores_path: models/scores/model_scores.json

model_evaluation:
  train_array_path: data/train/train_array.npy
  test_array_path: data/test/test_array.npy
  model_path: models/trained/lr_model.pkl
  scores_path: models/scores/lr_model_scores.json
  predictions_dir: models/predictions/