decision_tree:
  criterion: ["gini", "entropy", "log_loss"]
  splitter: ["best", "random"]
  max_features: ["sqrt", "log2"]

random_forest:
  criterion: ["gini", "entropy", "log_loss"]
  max_features: ["sqrt", "log2"]
  n_estimators: [8, 16, 32, 64, 128, 256]